name: Update KnivesOutPC Version

on:
  schedule:
    # Trigger automatically every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants permissions to commit and push changes back to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Update Script
        run: python Site/KnviesOutPC.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Check if KnivesOutPC.txt was modified by the Python script
          if [ -n "$(git status --porcelain)" ]; then
            git add KnivesOutPC.txt
            git commit -m "chore: auto-update KnivesOutPC version via script"
            git push
          else
            echo "No changes detected. The text file is already up to date."
          fi
