name: Riot LOL

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-lol:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run Scraper Script
      run: python Site/Riot/Riot_LOL.py

    - name: Commit and Push Updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        
        git add Site/Riot/last_lol_patch.txt || true
        git add LeagueOfLegend.txt || true
        
        if git diff --staged --quiet; then
          echo "No changes found to push."
        else
          git commit -m "Update: New LoL Patch Notes Extracted"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
        fi
